name: CI Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      CLEAN_WORKSPACE:
        description: 'Clean workspace before checkout?'
        required: true
        default: 'Yes'
        type: choice
        options:
          - Yes
          - No
          - Not so sure

jobs:
  clean-workspace:
    if: ${{ github.event.inputs.CLEAN_WORKSPACE == 'Yes' }}
    runs-on: ubuntu-latest
    steps:
      - name: Clean Workspace
        run: rm -rf ${{ github.workspace }}/*

  checkout:
    needs: clean-workspace
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: main

  npm-install:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm install next

  npm-build:
    needs: npm-install
    runs-on: ubuntu-latest
    steps:
      - name: Build Application
        run: npm run build

  npm-start:
    needs: npm-build
    runs-on: ubuntu-latest
    steps:
      - name: Start Application
        run: npm run start

  notify:
    needs: [clean-workspace, checkout, npm-install, npm-build, npm-start]
    runs-on: ubuntu-latest
    steps:
      - name: Notify Status
        if: ${{ success() }}
        run: |
          echo "Job Success! Check the workflow logs."
          # Replace with your email-sending mechanism if needed
        else:
          echo "Job Failed! Check the workflow logs."
