name: CI Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

  npm-install:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm install
        working-directory: ./nextjs-animated-slider # Update this if your project is in a subfolder

  npm-build:
    runs-on: ubuntu-latest
    needs: npm-install
    steps:
      - name: Build Application
        run: npm run build
        working-directory: ./nextjs-animated-slider # Update this if your project is in a subfolder

  npm-start:
    runs-on: ubuntu-latest
    needs: npm-build
    steps:
      - name: Start Application
        run: npm run start
        working-directory: ./nextjs-animated-slider # Update this if your project is in a subfolder
