name: CI Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: main

  npm-install:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm install next

  npm-build:
    needs: npm-install
    runs-on: ubuntu-latest
    steps:
      - name: Build Application
        run: npm run build

  npm-start:
    needs: npm-build
    runs-on: ubuntu-latest
    steps:
      - name: Start Application
        run: npm run start

  notify-success:
    if: ${{ success() }}
    needs: [checkout, npm-install, npm-build, npm-start]
    runs-on: ubuntu-latest
    steps:
      - name: Notify Success
        run: echo "Job Success! Check the workflow logs."

  notify-failure:
    if: ${{ failure() }}
    needs: [checkout, npm-install, npm-build, npm-start]
    runs-on: ubuntu-latest
    steps:
      - name: Notify Failure
        run: echo "Job Failed! Check the workflow logs."
