name: CI Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: main

  validate-installation:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Run auto.sh
        run: bash auto.sh

  notify-success:
    if: ${{ success() }}
    needs: validate-installation
    runs-on: ubuntu-latest
    steps:
      - name: Notify Success
        run: |
          echo "SUCCESS: Job '${{ github.job }} [${{ github.run_id }}]'"
          echo "Check the console output: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "SUCCESS: Job '${{ github.job }} [${{ github.run_id }}]'"
          body: |
            <p>SUCCESS: Job '${{ github.job }} [${{ github.run_id }}]'</p>
            <p>Check the console output: <a href='${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'>${{ github.job }} [${{ github.run_id }}]</a></p>
          to: avsvishal94@gmail.com

  notify-failure:
    if: ${{ failure() }}
    needs: validate-installation
    runs-on: ubuntu-latest
    steps:
      - name: Notify Failure
        run: |
          echo "FAIL: Job '${{ github.job }} [${{ github.run_id }}]'"
          echo "Check the console output: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "FAIL: Job '${{ github.job }} [${{ github.run_id }}]'"
          body: |
            <p>FAIL: Job '${{ github.job }} [${{ github.run_id }}]'</p>
            <p>Check the console output: <a href='${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'>${{ github.job }} [${{ github.run_id }}]</a></p>
          to: avsvishal94@gmail.com
